server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # 包含zipkin和sleuth ,链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
    probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.10.8.101:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: bwca_2020#@a

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: payment8001 # 主机名称
    prefer-ip-address: true # 显示IP地址
#    # eureka客户端向注册中心发送心跳时间间隔,单位：秒（默认 30s）
#    lease-renewal-interval-in-seconds: 1
#    # eureka服务端收到最后一次心跳后等待时间上限，单位是秒，默认为90s，超时将剔除服务
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities